config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' => 'sessions#create'

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users, only: [:new, :create]

  resources :lists do
    resources :items
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :description

  belongs_to :list

  STATUS = {
    incomplete: 0,
    complete: 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :name
  
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :email, message: "Please enter an email address"
  validates_uniqueness_of :email, message: "That email is taken, please use another"

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(email: auth_hash["email"]).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authentication_required
    if !logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      respond_to do |f|
        f.html {redirect_to list_path(@list)}
        f.json { render :json => @item }
      end
    else
      render "lists/show"
    end
  end

  # PATCH '/lists/:list_id/items/:id'
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)

    redirect_to list_path(@item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |f|
      f.json { render :json => @item}
      f.html {redirect_to list_path(@item.list)}
    end
  end

  private
    def item_params
      params.require(:item).permit(:description, :list_id, :status)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authentication_required

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @item = Item.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_url(@list)
    else
      @lists = List.all
      render :index
    end
  end

  private
    def list_params
      params.require(:list).permit(:name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]["info"]
      user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = user.id
      redirect_to root_path
    else
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        render 'sessions/new'
      end
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'users/new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def li_for_item(item)
    content_tag_for:li, item, class: li_class_for_item(item) do
      yield
    end
  end

  def form_for_item_status(item)
    form_for([@list, item]) do |f|
      f.check_box :status, class: "toggle", checked: item.complete?
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
  <div class="view">
    <%= form_for_item_status(item) %>
    <label><%= item.description %></label>

    <%= button_to "x", list_item_path(item.list, item), method: "delete", class: "destroy" %>

  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMvcCodealong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">

  <header class="header">
    <h1>Your Lists</h1>
    <%= form_for(@list) do |f| %>
      <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Make a new list") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>

  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
          <label><%= link_to list.name, list_path(list) %></label>
        </div>
      </li>
      <% end %>
    </ul>
  </section>

  <footer class="footer">
  </footer>

</section>

<footer class="info">
  <p>
    You're logged in as: <%= current_user.email %>
  </p>
  <%= link_to 'Logout', logout_path %>
</footer>

app/views/lists/show.html.erb
<section class="todoapp">

  <header class="header">
    <h1><%= @list.name %></h1>
    <%= form_for([@list, @item]) do |f| %>
      <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Add an item") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>

  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Add an item</label>
    <ul class="todo-list">
      <%= render collection: @list.items, partial: 'items/item_li', as: :item %>
    </ul>
  </section>

  <footer class="footer">
  </footer>

</section>

<script id="item-template" type="text/x-handlebars-template">
  <li class="item" id="item_{{id}}">
    <div class="view">
      <form class="edit_item" id="edit_item_{{id}}" action="/lists/<%= @list.id %>/items/{{id}}" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="_method" value="patch">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input name="item[status]" type="hidden" value="0"><input class="toggle" type="checkbox" value="1" name="item[status]" id="item_status"></form>

      <label>{{description}}</label>

      <form class="button_to" method="post" action="/lists/<%= @list.id %>/items/{{id}}">
        <input type="hidden" name="_method" value="delete">
        <input class="destroy" type="submit" value="x">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      </form>
    </div>
  </li>
</script>

app/views/users/new.html.erb
<section class="todoapp">

  <header class="header">
    <h1>Signup!</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :email, class: "new-todo", placeholder: "Sign up with your email address:" %>
      <%= f.text_field :password, class: "new-todo", placeholder: "Choose your password" %>
      <%= f.submit %>
    <% end %>

  </header>



  <footer class="footer">
  </footer>

</section>